function fpause = Pause
fpause = figure('Visible','off',...
    'Name','Paused',...
    'Position',[535 275 500 300]);

txt = uicontrol('Style','text',...
    'Position',[150 253 205 30],...
    'String',"You've paused your Quest!",...
    'FontName','Poor Richard',...
    'FontSize',15);


Name1= uicontrol('Style','pushbutton', 'String','Return to the Carnage!',...
    'FontName','Poor Richard',...
    'FontSize',12,...
    'Position',[150 100 200 70],...
    'Callback', @Begin);

Start4= uicontrol('Style','pushbutton', 'String','Begin',...
    'Visible','off',...
    'FontName','Poor Richard',...
    'FontSize',12,...
    'Position',[223 100 55 30],...
    'Callback', @Begin);

fpause.Visible = 'on';

    function Begin(~,~)
        pause(1/3)
        close(fpause)
        
    end
end