function f1 = Start
f1 = figure('Visible','off',...
    'Name','Welcome',...
    'Position',[535 275 500 300]);

txt = uicontrol('Style','text',...
    'Position',[158 273 185 30],...
    'String','Welcome to your Quest!',...
    'FontName','Poor Richard',...
    'FontSize',15);

Name = uicontrol('Style','edit',...
    'Position',[168 243 100 30]);

Name1= uicontrol('Style','pushbutton', 'String','Enter',...
    'FontName','Poor Richard',...
    'FontSize',12,...
    'Position',[268 243 50 30],...
    'Callback', @Enter);
Start2 = uicontrol('Style','text','Visible','off',...
    'String','Your name is Dr. Busick, eh?',...
    'FontName','Poor Richard',...
    'FontSize',14,...
    'Position',[158 253 200 30]);

Start3 = uicontrol('Style','text','Visible','off',...
    'String','Well, there is something for you to do',...
    'FontName','Poor Richard',...
    'FontSize',14,...
    'Position',[120 223 275 30]);

HP = uicontrol('Style','text','Visible','off',...
    'String','Vitality: 1',...
    'FontName','Poor Richard',...
    'FontSize',14,...
    'Position',[200 190 100 30]);
ST = uicontrol('Style','text','Visible','off',...
    'String','Strength: 1',...
    'FontName','Poor Richard',...
    'FontSize',14,...
    'Position',[200 160 100 30]);
DX = uicontrol('Style','text','Visible','off',...
    'String','Dexterity: 1',...
    'FontName','Poor Richard',...
    'FontSize',14,...
    'Position',[200 130 100 30]);


Start4= uicontrol('Style','pushbutton', 'String','Begin',...
    'Visible','off',...
    'FontName','Poor Richard',...
    'FontSize',12,...
    'Position',[223 100 55 30],...
    'Callback', @Begin);

f1.Visible = 'on';

    function Enter(~,~)
        pause(1/4)
        Name.Visible = 'off';
        Name1.Visible = 'off';
        Start2.Visible = 'on';
        Start3.Visible = 'on';
        txt.Visible = 'off';
        Start4.Visible = 'on';
        HP.Visible = 'on';
        ST.Visible = 'on';
        DX.Visible = 'on';

    end
    function Begin(~,~)
        pause(1/3)
        close(f1)
        
    end
end